theme = "catppuccin-frappe"
confirm-before-quit = false
padding-x = 8
padding-y = [2, 0]

[cursor]
shape = 'block'

[window]
mode = "Maximized"

[fonts]
family = "Maple Mono NF CN"
size = 20
[fonts.regular]
family = "Maple Mono NF CN"
style = "Normal"
weight = 480

[navigation]
mode = "Bookmark"
clickable = false
hide-if-single = true
use-current-path = true

