# startup game
[[tasks]]
type = "StartUp"
params = { client_type = "Official", start_game_enabled = true }

[[tasks]]
type = "Recruit"
[tasks.params]
refresh = true
select = [4]
confirm = [3, 4]
times = 4

[[tasks]]
type = "Infrast"
[tasks.params]
facility = ["Mfg", "Trade", "Control", "Power", "Reception", "Office", "Dorm"]
# "_NotUse"、"Money"、"SyntheticJade"、"CombatRecord"、"PureGold"、"OriginStone"、"Chip"
drones = "PureGold"

[[tasks]]
type = "Mall"
[tasks.params]
shopping = true
buy_first = ["招聘许可", "龙门币"]
blacklist = ["碳", "家具", "加急许可"]

[[tasks]]
type = "Award"

# close game
# [[tasks]]
# type = "CloseDown"
